package rust

import (
	"fmt"
	"io"
	"strings"

	"github.com/lemon-mint/vstruct/ir"
)

func Generate(w io.Writer, i *ir.IR, packageName string) error {
	var codedataBuf strings.Builder
	writeEnums(&codedataBuf, i)
	writeStructs(&codedataBuf, i)
	writeAliases(&codedataBuf, i)
	output := fmt.Sprintf(
		`#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(non_snake_case)]

use std::fmt;

// Code generated by vstruct. DO NOT EDIT.
// Package Name: %s

%s
`,
		packageName,
		codedataBuf.String(),
	)
	_, err := w.Write([]byte(output))
	return err
}
